# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.srcs/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0.xci
# IP: The module: 'demo1_db_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.srcs/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0.xci
# IP: The module: 'demo1_db_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo1_db_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
