# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/demo1_db/demo1_db.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db || ORIG_REF_NAME==demo1_db} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_processing_system7_0_0/demo1_db_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_processing_system7_0_0 || ORIG_REF_NAME==demo1_db_processing_system7_0_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_axi_mem_intercon_0/demo1_db_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_axi_mem_intercon_0 || ORIG_REF_NAME==demo1_db_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_rst_ps7_0_100M_0/demo1_db_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_rst_ps7_0_100M_0 || ORIG_REF_NAME==demo1_db_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_example_0_0/demo1_db_example_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_example_0_0 || ORIG_REF_NAME==demo1_db_example_0_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_ps7_0_axi_periph_0/demo1_db_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_ps7_0_axi_periph_0 || ORIG_REF_NAME==demo1_db_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_auto_pc_0/demo1_db_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_auto_pc_0 || ORIG_REF_NAME==demo1_db_auto_pc_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_auto_us_0/demo1_db_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_auto_us_0 || ORIG_REF_NAME==demo1_db_auto_us_0} -quiet] -quiet

# IP: bd/demo1_db/ip/demo1_db_auto_pc_1/demo1_db_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==demo1_db_auto_pc_1 || ORIG_REF_NAME==demo1_db_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/dianhsu/Desktop/axi-demo/demo1/vivado/demo1/demo1.gen/sources_1/bd/demo1_db/demo1_db_ooc.xdc
